name: semantic-pr-title
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat, fix, perf, refactor, docs, chore, build, ci
          requireScope: false
          wip: true
